"""add users and personas

Revision ID: 38c44b86e646
Revises: 7ec413fcf4c3
Create Date: 2026-09-21 11:13:49.771842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38c44b86e646"
down_revision: str | Sequence[str] | None = "7ec413fcf4c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.add_column("chat_sessions", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("chat_sessions", sa.Column("persona_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_chat_sessions_persona_id"),
        "chat_sessions",
        ["persona_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_sessions_user_id"), "chat_sessions", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_chat_sessions_persona_id_personas",
        "chat_sessions",
        "personas",
        ["persona_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_chat_sessions_user_id_users",
        "chat_sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_chat_sessions_user_id_users", "chat_sessions", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_chat_sessions_persona_id_personas", "chat_sessions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_persona_id"), table_name="chat_sessions")
    op.drop_column("chat_sessions", "persona_id")
    op.drop_column("chat_sessions", "user_id")
    op.drop_table("users")
    op.drop_table("personas")
    # ### end Alembic commands ###
